# Which Xen domain (domain name) to attach to (LibVMI)
domain_name: "ubuntu-20-04-new-kernel"

# How long the entire introspection window should last (in miliseconds)
monitor:
  window_ms: 100000
  state_sampling_ms: 1000

# Which detection services to dispatch.
# Tasks are split into two categories:
# 1. State polling tasks (e.g., task_module_list)
# 2. Event-driven tasks (e.g., mem_event)
features:
  state:
    # # Direct mapping to enum
    # - id: STATE_KERNEL_MODULE_LIST
    # - id: STATE_PROCESS_LIST
    # - id: STATE_IDT_TABLE
    # - id: STATE_SYSCALL_TABLE
    # Modified PoC does not work for this :(, maybe try on the old kernel
    # - id: STATE_MSR_REGISTERS
    # - id: STATE_KALLSYMS_SYMBOLS
    # # This approach needs modification.
    # - id: STATE_KERNEL_CODE_INTEGRITY_CHECK
    - id: STATE_IO_URING_ARTIFACTS
    - id: STATE_NETWORK_TRACE
  event:
    - id: EVENT_CR0_WRITE
