/**
 * @file offsets.h
 * @author Myrsini Gkolemi
 * @brief This file contains offsets used for introspection.
 * @version 0.0
 * @date 2025-08-31
 * 
 * @copyright Copyright (c) 2025
 * 
 */
#ifndef OFFSETS_H
#define OFFSETS_H

// The offsets were extracted using pahole on vmlinux-5.15.0-139-generic.

#define LINUX_CRED_OFFSET 0XBA8
#define LINUX_STATE_OFFSET 0x18
#define LINUX_UID_OFFSET   0x8
#define LINUX_GID_OFFSET   0xC
#define LINUX_EUID_OFFSET  0x18
#define LINUX_EGID_OFFSET  0x1C


#define LINUX_INET_HASHINFO_EHASH_OFFSET 0x0
#define LINUX_INET_HASHINFO_EHASH_MASK_OFFSET 0x10
#define LINUX_INET_HASHINFO_LHASH2_OFFSET 0x30

#define LINUX_SOCK_COMMON_OFFSET 0x0

#define LINUX_SKC_DADDR_OFFSET 0x0
#define LINUX_SKC_RCV_SADDR_OFFSET 0x4
#define LINUX_SKC_DPORT_OFFSET 0xC
#define LINUX_SKC_NUM_OFFSET 0xE
#define LINUX_SKC_STATE_OFFSET 0x12
#define LINUX_SKC_NODE_OFFSET 0x68
#define LINUX_SKC_NODE_NEXT_OFFSET 0x0

#define LINUX_NET_NF_OFFSET 0x40
#define LINUX_NF_HOOKS_OFFSET 0x0

#define LINUX_MODULE_LIST_OFFSET 0x08
#define LINUX_MODULE_NAME_OFFSET 0x18
#define LINUX_MODULE_STATE_OFFSET 0x00

#define LINUX_NETNF_HOOKS_IPV4_OFFSET 0x78
#define LINUX_NETNF_HOOKS_IPV6_OFFSET 0xA0
#define LINUX_NETNF_HOOKS_ARP_OFFSET 0xC8
#define LINUX_NETNF_HOOKS_BRIDGE_OFFSET 0xE0

#define LINUX_NF_HOOK_ENTRIES_NUM_OFFSET 0x0
#define LINUX_NF_HOOK_ENTRIES_PAD 0x8
#define LINUX_NF_HOOK_ENTRY_SIZE 0x10

#define LINUX_OFFSET_TASK_IO_URING 0xC08
#define LINUX_OFFSET_IO_URING_TASK_LAST 0X20
#define LINUX_OFFSET_IO_RING_CTX_RINGS 0XD0
#define LINUX_OFFSET_IO_RINGS_SQ_ENTRIES 0X10
#define LINUX_OFFSET_IO_RINGS_CQ_ENTRIES 0X14


#define LINUX_FTRACE_OPS_FUNC_OFFSET 0x00
#define LINUX_FTRACE_OPS_NEXT_OFFSET 0x08
#define LINUX_FTRACE_OPS_FLAGS_OFFSET 0x10
#define LINUX_FTRACE_OPS_PRIVATE_OFFSET 0x18
#define LINUX_FTRACE_OPS_SAVED_FUNC_OFFSET 0x20
#define LINUX_FTRACE_OPS_FUNC_HASH_OFFSET 0x58
#define LINUX_FTRACE_OPS_TRAMPOLINE_OFFSET 0x90
#define LINUX_FTRACE_OPS_TRAMPOLINE_SIZE_OFFSET 0x98
#define LINUX_FTRACE_OPS_LIST_OFFSET 0xA0

#define LINUX_PTR_SIZE 8

#define LINUX_BPF_PROG_TYPE_OFFSET 0x04
#define LINUX_BPF_PROG_JITED_PROG_LEN_OFFSET 0x10
#define LINUX_BPF_PROG_AUX_OFFSET 0x38
#define LINUX_BPF_PROG_AUX_ID_OFFSET 0x20
#define LINUX_BPF_PROG_AUX_NAME_OFFSET 0x210
#define LINUX_BPF_OBJ_NAME_LEN 16

#define LINUX_BPF_MAP_ID_OFFSET 0x34
#define LINUX_BPF_MAP_TYPE_OFFSET 0x18
#define LINUX_BPF_MAP_KEY_SIZE_OFFSET 0x1C
#define LINUX_BPF_MAP_VALUE_SIZE_OFFSET 0x20
#define LINUX_BPF_MAP_MAX_ENTRIES_OFFSET 0x24
#define LINUX_BPF_MAP_FLAGS_OFFSET 0x28
#define LINUX_BPF_MAP_NAME_OFFSET 0x58

#define LINUX_PTREGS_OFF_R10      0x38
#define LINUX_PTREGS_OFF_R9       0x40
#define LINUX_PTREGS_OFF_R8       0x48
#define LINUX_PTREGS_OFF_AX       0x50
#define LINUX_PTREGS_OFF_CX       0x58
#define LINUX_PTREGS_OFF_DX       0x60
#define LINUX_PTREGS_OFF_SI       0x68
#define LINUX_PTREGS_OFF_DI       0x70
#define LINUX_PTREGS_OFF_ORIG_AX  0x78
#define LINUX_PTREGS_OFF_IP       0x80
#define LINUX_PTREGS_OFF_FLAGS    0x90
#define LINUX_PTREGS_OFF_SP       0x98

#endif  // OFFSETS_H
